### ISSUE TITLE
Cannot find file

### ISSUE THREAD

**Issue by Destiny-Dream1** [Jamy-L/handheld-sr-satellite#3]
Hello, I am interested in your research. After reviewing your CVPRW paper, I would like to try running your code. However, I cannot find the dataset or the 'noised.npy' and 'ratios_noised_20.npy' files mentioned in the 'example.py'. Could you please provide the location of these files? Thank you so much.

**Comment by Jamy-L** [comment]
Hi, 

These files were too large to fit in the repo, you will find them in [this release](https://github.com/Jamy-L/handheld-sr-satellite/releases/tag/1.0), in the synthetic burst folder.

**Comment by Destiny-Dream1** [comment]
Thank you for promptly answering my questions, and I have successfully found it. Additionally, I would like to inquire whether the algorithm can be directly applied to grayscale PNG files without using npy files. Thank you.

**Comment by Jamy-L** [comment]
This was not implemented because the images we had as well as the exposure times were given in .npy format. You can still use cv2 to read the png as a numpy array before feeding the algorithm. Something around the lines of:

```python
import numpy as np
import cv2
import os
from pathlib import Path

path = Path(png_folder)

burst = []
for png_path in os.listdir(path):
    im_path = path / png_path
    burst.append(cv2.imread(im_path.asposix()))
exposures = np.load(exposure_path)
burst = np.stack(burst)
```
(This probably needs a few adjustments)

**Comment by Destiny-Dream1** [comment]
OK, I understand. Thank you for your assistance. I will try the methods you provided again. Lastly, may I inquire where I can find the high-resolution images to calculate PSNR and SSIM?(I am able to execute the program now) 
Thanks once more~

**Comment by Destiny-Dream1** [comment]
Furthermore, I noticed that the [ICA website](url: https://github.com/Jamy-L/handheld-sr-satellite/blob/main/link) is currently displaying '404 page not found.' I wonder if I could trouble you to provide the relevant information again, plz. 

Also, when testing with 
params={
        "scale":2,
        'base detail' : True, # Whether to use the base detail decomposition or not
        'alignment' : 'patch ICA', # 'Fnet', 'ICA', 'patch ICA', the alignment methode
        }
I encountered the following error. I would like to confirm with you whether this issue is due to a misconfiguration on my end. Thank you so much.

![question](https://github.com/Jamy-L/handheld-sr-satellite/assets/72513073/40a16089-a792-44b0-ac80-5c730a10f96f)

**Comment by Jamy-L** [comment]
Thank you for pointing out this bug, I have pushed a fix that should solve it, it came from a typo.

I can't recall exactly where the icaflow package can be found. I will ask around and point back to it as soon as I know!

**Comment by Destiny-Dream1** [comment]
Thank you so much for your prompt response. In conclusion, I have a question regarding the reference image mentioned in the CVPRW paper. Would it be possible for you to provide it to facilitate the computation of PSNR and SSIM? Your assistance is greatly appreciated.

**Comment by Destiny-Dream1** [comment]
Thank you so much for your prompt response. In conclusion, I have a question regarding the reference image mentioned in the CVPRW paper. Would it be possible for you to provide it to facilitate the computation of PSNR and SSIM? Your assistance is greatly appreciated.

**Comment by Jamy-L** [comment]
The reference is frame is actually the frame of the burst that serves as template for the alignment (the first frame if I recall correctly). The image we plot as "reference" in the paper is the reference frame upscaled using nearest neighbour interpolation.

**Comment by Destiny-Dream1** [comment]
I understand, thank you very much for your detailed response to my questions. I also hope that my inquiries will be helpful to others reading the paper in the future. Once again, I appreciate the author's thoughtful replies. :)

**Comment by Destiny-Dream1** [comment]
Hello, author. I apologize for coming back with another question recently. I would appreciate it if you could help clarify or provide some hints. The issue pertains to the output images having black borders on all four sides, as shown in the attached image below(I put the two sides for example). I am unsure about which part I can modify to address this problem. Once again, thank you for your assistance.
![image](https://github.com/Jamy-L/handheld-sr-satellite/assets/72513073/554694f2-b726-49af-afe7-308a6f244d69)
